### ISSUE TITLE
Automatic Door toggle keybind can only disable, won't re-enable

### ISSUE THREAD

**Issue by TriggerHappyBro** [eideehi/valheim-automatics#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.0

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### What happened?

Pressed Automatic Door enable/disable keybind and it disables as expected but pressing it again does nothing. If I also run the configuration manager mod I can re-enable it that way and use the keybind to disable it again, but again not re-enable.

### Steps to reproduce the bug

1. Enable Automatic Door (optionally, observe it working as intended)
2. Bind a key to the Automatic Door enable/disable toggle
3. Press keybind for Automatic Door enable/disable toggle (observe disable message and non-auto doors)
4. Press keybind again, note **lack** of enable message and still non-automatic doors

**Comment by turnerlewis** [comment]
Just came here to say I also have this issue, exact same circumstances. It won't re-enable.

**Comment by eideehi** [comment]
This bug has been fixed in commit 5bddedc1244bb206e14ca1233af756c231d52f22.

Please wait for the bug fix release. Thank you for reporting the bug.
