### ISSUE TITLE
Config - double negatives & Config Manager 

### ISSUE THREAD

**Issue by luxzg** [eideehi/valheim-automatics#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.0

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### What happened?

Not exactly a bug as such, but double negatives seem to confuse Config Manager. I was setting auto pickup to FALSE (in config manager) but it ended up being "disable = false" instead slightly more expected "enable = true" for enabling the feature. I've ended up being so annoyed by autopickup (kept picking up stuff mid fight overburdening me), until I opened conf in text editor and noticed that.

Anyway, since you suggest using config manager you might look into clearing that up a bit to make it little bit easier to understand.

### Steps to reproduce the bug

Configure individual modules on/off using Config Manager

**Comment by eideehi** [comment]
This issue wasn't a bug, but I addressed it in commit 0a537be405f5867cb968ebd02bb3864592e24a56 as I thought it was an important requirement.
