### ISSUE TITLE
[ Title that succinctly describes the bug ]

### ISSUE THREAD

**Issue by 2077141408** [eideehi/valheim-automatics#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.2

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### List of mods to reproduce bug

游戏版本更新，模组无法使用

### What happened?

游戏版本更新，模组无法使用

### Steps to reproduce the bug

游戏版本更新，模组无法使用

**Comment by eideehi** [comment]
Closed due to invalid Issue.
