### ISSUE TITLE
Not compatible with the Monmod patch

### ISSUE THREAD

**Issue by 2077141408** [eideehi/valheim-automatics#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.3

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### List of mods to reproduce bug

![Y1%GPA%K %XPDX6RG$B9GTX](https://user-images.githubusercontent.com/90947817/228668685-68d1bed1-7740-4d0a-8eb0-fbd323230c0c.png)

### What happened?

The auto module is not compatible with the HookGenPatcher, and the stack in the box has an error

### Steps to reproduce the bug

更新补丁后出现

### Logs and screenshots

![Y1%GPA%K %XPDX6RG$B9GTX](https://user-images.githubusercontent.com/90947817/228669069-68993332-2450-4e7f-b4c9-cba864eb01f6.png)

**Comment by eideehi** [comment]
#61 solved the issue.
