### ISSUE TITLE
Config file constantly being written in a loop

### ISSUE THREAD

**Issue by ZenDragonX** [eideehi/valheim-automatics#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.4

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### What happened?

Watch the config file in a separate editor such as VSCode.  It constantly is flushed and rewritten while the game is running.  This is wasting needless IO operations.  Should not be writing the config file constantly unless something changed.

### Steps to reproduce the bug

Run the game with mod installed.
Watch the config file rewrite over and over again.

**Comment by eideehi** [comment]
I investigated this matter and will report the results.
This is not a bug, but a specification of the configuration manager. BepInEx.ConfigurationManager overwrites all configurations every time the game is started. If you check the update date of other mod configurations, you will see that they have all been changed to the last time Valheim was started.

**Comment by eideehi** [comment]
If this issue is about "configurations being continuously overwritten during game startup" please provide your configuration. I could not reproduce it on my end.
