### ISSUE TITLE
Duplicate Pin's being created on top of each other.

### ISSUE THREAD

**Issue by GoofyWarriorGuy** [eideehi/valheim-automatics#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.4

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### What happened?

I've noticed that Map Pins are duplicating when I leave an area and then return, it puts a new Pin on top of the current Pin with exactly the same name.
Obviously this only happens when 'Save Static Object Pins' is Enabled.
For areas I frequent a lot I've seen 7 or 8 Pin's over top of each other and the Pin and Text seem to have like a Drop Shadow effect on them. You can 'Right Click' remove the overlapping Pins but it shouldn't be stacking up like this.

### Steps to reproduce the bug

1. Enter an area where a Static Object would be Pinned.
2. Leave the area
3. Return to the same area and a new Pin will be created over top of the previous one.

**Comment by eideehi** [comment]
I have confirmed the issue. I am working on fixing it.

**Comment by eideehi** [comment]
I have made fixes in version 1.4.5. I could no longer reproduce the issue in my environment, but please let us know if the bug still occurs.
