### ISSUE TITLE
Static-mapped pins disappear immediately upon creation

### ISSUE THREAD

**Issue by riordain87** [eideehi/valheim-automatics#56]
### Is there an existing issue for this bug?

- [X] I have searched the existing issue

### Mod version

1.4.5

### What happened?

Hej!  I have auto-pinning of static objects enabled (blueberries, thistle, copper deposit, etc.), and have had for a couple months.  I also have the option enabled to NOT save them, since I enjoy being able to click on the ones I want to save.  Historical gameplay is: I approach a copper deposit, a static pin is added, and if I do not click it, when I walk away, the pin goes away, but if I do click it, it stays there even if I walk away.
Since updating today, static pins are disappearing immediately upon being created.  Default creation time for the pins is 0.25s, so there is quite a bit of flickering when it comes to creating nearby pins because they will be created ever quarter second and then disappear a quarter second later or similar... and repeat indefinitely.  There is no time to click it to save the pin like I'm used to.
I can turn "Save Static Object Pins" on, and it will save them indefinitely (not desired for me).  But as soon as I turn that option back off, the bug behavior starts again.
Thanks for looking into this!

### List of Mods required to reproduce the bug

Automatics

### Steps to reproduce the bug

1. Have "Automatic Mapping" enabled.
2. Have "Static Object Search Range" >0.
3. Have "Allow Pinning Flora/Mineral" enabled.
4. Have "Save Static Object Pins" disabled.
5. Get close to something that should be pinned like a copper deposit.
6. Watch the pins get created and immediately destroyed.

**Comment by eideehi** [comment]
Thank you for reporting the bug. To be honest, I know it can be a hassle to fill out this issue template, but I appreciate that you took the time to do so thoroughly. Regarding this bug, it has been fixed in version 1.4.6, so please check it out.

**Comment by riordain87** [comment]
Thank you!  I'm very excited.  Have a good one.
