### ISSUE TITLE
After Valheim patch 0.217.14, Automatics has broken the game

### ISSUE THREAD

**Issue by neket3** [eideehi/valheim-automatics#60]
### Is there an existing issue for this bug?

- [X] I have searched the existing issue

### Mod version

1.4.8

### What happened?

When you start the game, a console opens that cannot be closed

### List of Mods required to reproduce the bug

Automatics

### Steps to reproduce the bug

1. Install Automatics
2. Start the game
3. ???
4. Don't play game

### File attachments

![Screenshot_1](https://github.com/eideehi/valheim-automatics/assets/142952878/b24a5b7c-f5c1-443c-81d8-9a02751f8ce3)

**Comment by panchitojr** [comment]
I am also having the same exact issue :'(

This is my favorite mod

**Comment by Aromack** [comment]
Me too, I have the same issue and also love this mod. It makes valheim so much less tedious.

**Comment by lennysme** [comment]
I'm having the same issue with the mod; thank you so much for dedicating time to making an excellent mod that compensates for sooooo much of the tedium in the game!

**Comment by LordDelacroix** [comment]
Are the changes on Nexus Mods yet?

**Comment by CelticMoonstar** [comment]
Having the same issue as well. Hope this is resolved soon, really like this mod. 
(downloaded from Nexus.)

**Comment by eideehi** [comment]
Version 1.5.0, including commit a7f65d68929d31b4b7ac73b42ff6efab1e25483d to resolve this issue, has not been released yet due to remaining tasks. Please wait a bit longer until the release of 1.5.0 for completion.

**Comment by LordDelacroix** [comment]
Do you have a patreon page?

**Comment by Aromack** [comment]
Better yet use "GiveSendGo". Forget patrion they let ideology get in the
way of business.

**Comment by wrhadie** [comment]
still waiting for update 😕

**Comment by panchitojr** [comment]
He/she is working on it. Wait patiently.

**Comment by wrhadie** [comment]
this project has now been abandoned. 🙃

**Comment by eideehi** [comment]
I haven't had much time for mod development lately, so it's been delayed quite a bit, but I just released version 1.5.0 that works with the latest Valheim environment. I appreciate everyone's patience.
