### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by LordDelacroix** [eideehi/valheim-automatics#61]
### Is there an existing issue for this bug?

- [X] I have searched the existing issue

### Mod version

1.5.0

### What happened?

Install Item Drawers and build one (need 10 fine wood) drop items and:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Automatics.Patches.Container_Awake_Postfix (Container __instance, ZNetView ___m_nview) (at <0b650f0721424348b7292b3ac996ec5b>:0)
(wrapper dynamic-method) Container.DMD<Container::Awake>(Container)
UnityEngine.Object:Instantiate(GameObject)
Player:DMD<Player::SetupPlacementGhost>(Player)
MonoMod.Utils.DynamicMethodDefinition:Trampoline<Player::SetupPlacementGhost>?-1485527040(Player)
PlanBuild.Blueprints.BlueprintManager:Player_SetupPlacementGhost(orig_SetupPlacementGhost, Player)
MonoMod.Utils.DynamicMethodDefinition:Hook<Player::SetupPlacementGhost>?-79421824(Player)
MonoMod.Utils.DynamicMethodDefinition:Trampoline<Player::SetupPlacementGhost>?-1281691648(Player)
PlanBuild.Plans.PlanManager:Player_SetupPlacementGhost(orig_SetupPlacementGhost, Player)
MonoMod.Utils.DynamicMethodDefinition:Hook<Player::SetupPlacementGhost>?693326208(Player)
Player:UpdateAvailablePiecesList()
Player:DMD<Player::SetPlaceMode>(Player, PieceTable)
Humanoid:SetupEquipment()
Humanoid:DMD<Humanoid::EquipItem>(Humanoid, ItemData, Boolean)
MonoMod.Utils.DynamicMethodDefinition:Trampoline<Humanoid::EquipItem>?1544854528(Humanoid, ItemData, Boolean)
PlanBuild.Blueprints.BlueprintManager:Humanoid_EquipItem(orig_EquipItem, Humanoid, ItemData, Boolean)
MonoMod.Utils.DynamicMethodDefinition:Hook<Humanoid::EquipItem>?-1227717376(Humanoid, ItemData, Boolean)
Player:ToggleEquipped(ItemData)
Humanoid:UseItem(Inventory, ItemData, Boolean)
Player:DMD<Player::UseHotbarItem>(Player, Int32)
Player:DMD<Player::Update>(Player)

### List of Mods required to reproduce the bug

Item Drawers 0.5.6

### Steps to reproduce the bug

after building one and noting the exception, just drop some items that should go to an item drawer and you will the exception above.

**Comment by eideehi** [comment]
Thank you for submitting the bug report. I have just released version 1.5.1, which addresses this issue.

Your bug report was concise and perfectly met the requirements, allowing me to take immediate action. I deeply appreciate your dedication.

**Comment by LordDelacroix** [comment]
I am a developer and have been for 51 years. I know what it's like to get a bug report what says "It blew up" and no OTHER information of any sort!

Thank for your dedication in keeping this REQUIRED (for me at least) MOD alive!  

Now - how can I contribute to your cause?

**Comment by eideehi** [comment]
Wow, you're a senior figure! It makes sense that your bug report was perfect.
This mod is essential to me as well (although I haven't had much time for gaming lately...), so I'm committed to continuing maintenance, even if it's at a slower pace.

\> Now - how can I contribute to your cause?
Your words of gratitude are more than enough. Of course, pull requests are always welcome anytime.
